services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bd2-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./dataset:/app/dataset:ro
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bd2-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
